"""Phase 4: Close review renderer — thin wrapper.

Close review content is already generated by review.py as a structured
artifact (title + body). This module provides a pure rendering helper
for when you want to render review summaries from TradingState.
"""

from __future__ import annotations

from typing import Any


def render_close_review_summary(
    *,
    trade_date: str,
    holdings_summary: list[str] | None = None,
    trigger_summary: list[str] | None = None,
    signal_quality: str | None = None,
    opportunity_verification: str | None = None,
    next_actions: list[str] | None = None,
) -> str:
    """Render a close review summary from pre-computed sections.

    Each section is a pre-formatted list of lines. This function assembles them.
    """
    sections: list[tuple[str, list[str] | None]] = [
        ("📊 持仓回顾", holdings_summary),
        ("🎯 触发单状态", trigger_summary),
        ("📈 信号质量", [signal_quality] if signal_quality else None),
        ("📘 主动机会验证", [opportunity_verification] if opportunity_verification else None),
        ("📋 明日优先动作", next_actions),
    ]

    lines = [f"📋 收盘复盘 {trade_date}"]
    for title, content in sections:
        if content:
            lines.append(f"\n【{title}】")
            lines.extend(content)

    return "\n".join(lines)
